apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cve-consumer-pdb
  namespace: {{ .Release.Namespace | quote }}  
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: {{- template "labels" .}}