apiVersion: apps/v1 
kind: Deployment                                  
metadata:
  name: {{ .Release.Name }}-web-cve-consumer 
  namespace: {{ .Release.Namespace | quote }}                  
  labels:
    {{- template "labels" .}}
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}                                 
  selector:
    matchLabels: 
      {{- include "labels" . | indent 2}}             
  template:                                      
    metadata:
      labels:                                    
        {{- include "labels" . | indent 4}} 
    spec:         
      initContainers:
      - name: {{ .Release.Name }}-init-web-cve-consumer
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: Always 
        volumeMounts:
        - name: config
          mountPath: "/config/"
      containers:
      - name: {{ .Release.Name }}-web-cve-consumer 
        image: "{{ .Values.consumerImage.repository }}:{{ .Values.consumerImage.tag }}"    
        imagePullPolicy: Always            
        ports:
          - name: http
            containerPort: {{ .Values.consumerImage.port | int }}                
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-postgres-secret  
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.consumerImage.port | int }}
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.consumerImage.port | int }}
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-liquibase-config
            items: 
              - key: "liquibase.properties"
                path: liquibase.properties
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
