apiVersion: v1
kind: Service
metadata:
  name: rag-service
  labels:
    app: rag
spec:
  type: ClusterIP
  selector:
    app: rag
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http


