apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rag-deployment
  labels:
    app: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
        - name: rag
          image: anuragnandre/rag:v1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-rag-secret
          ports:
            - containerPort: 8501
              name: http
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret